<?php
/**
 * PluginBaseController
 * 所有的插件都要继承此controller
 * @author xiongchuan <xiongchuan86@gmail.com>
 */
namespace zyh\plugins\components;

use yii\base\Application;
use yii\base\UnknownPropertyException;
use yii;
use yii\web\Controller;

class PluginController extends Controller
{
    public function init()
    {
        parent::init();
    }

    public function getViewPath()
    {
        return $this->module->getViewPath();
    }

    public function renderView($view, $params = [])
    {
        $realView = $this->id . '/' . $view;
        return $this->render($realView, $params); // TODO: Change the autogenerated stub
    }
}